services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: drawdb-backend
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      # Map local data directory to container for SQLite persistence
      - ${HOST_DATA_DIR:-./data/sqlite}:${CONTAINER_DATA_DIR:-/app/data}
      # Map configuration directory for database configs
      - ${HOST_CONFIG_DIR:-./data/config}:${CONTAINER_CONFIG_DIR:-/app/config}
    networks:
      - drawdb-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: drawdb-frontend
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - drawdb-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  drawdb-network:
    driver: bridge

volumes:
  sqlite-data:
    driver: local
  config-data:
    driver: local
